WIP on Issue 94-add-remove-update-lines-in-the-databases
CenterForDigitalHumanities/TPEN-services pull request #105
Opened 2024-04-15 16:04 UTC by BhanuKandula5030

What was changed?

**Updated Line endpoint routes :** 

1. **DELETE /line/:id:** Remove this Line from the annotation page.
2. **PUT /line/:id:** Replace this document with the payload of the request.

2024-04-22 13:56 UTC, BhanuKandula5030 commented
These are the Postman Screenshots of the response for the page requests append and prepend line 
<img width="645" alt="pagepm1" src="https://github.com/CenterForDigitalHumanities/TPEN-services/assets/113061241/81dc0bb9-1e0a-4121-95ec-166bb677d8ef">
<img width="647" alt="pagepm2" src="https://github.com/CenterForDigitalHumanities/TPEN-services/assets/113061241/64b27b7d-0cda-4501-aa3f-3d18259a889c">

2024-04-22 16:50 UTC, thehabes requested changes
Tests within your scope are failing.  Please make sure tests related to your scope (/line) are passing before you ask for review.  I do not see tests for the new endpoints you registered either.  All endpoints that intend to be merged with `development` must have some kind of useful test(s).  
> Your PR has been switched back to 'Draft' because you have not written these tests.

Found by running `npm run allTests` before looking at code.

![image](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/3287006/c794cef8-6dd4-40dd-94d6-cc5aa8273fd0)


![image](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/3287006/181255d6-b13c-4d16-86a9-f89d85f1e190)

2024-04-23 18:34 UTC, thehabes reviewed
I am running into a failed test when I use `npm run allTests`.  Look into this.
![image](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/3287006/1f5f5683-98fc-49d1-aaa3-028272f3bbd9)

Make sure you get this to a functional state.  Here is the test I performed.

I generated Annotation Collection https://devstore.rerum.io/v1/id/6627fc13a1162cbdb9d34a5d

I generated Annotation Page https://devstore.rerum.io/v1/id/6627fc3d5cc3848690279f7c and put it into the collection.  This page has no `items[]` yet.

I performed http://localhost:3009/page/627fc3d5cc3848690279f7c/appendLine which said successful
![image](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/3287006/5268f8b6-bff7-467a-b696-cfe767d831ee)

However, no update was performed against Annotation Page https://devstore.rerum.io/v1/id/6627fc3d5cc3848690279f7c.  It does not have a `next` item in history, and also does not have any `items[]` even though I just added one.

It says it created two Annotations when I only provided one.  

![image](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/3287006/daa753af-4d97-4215-860c-2f64df4cd316)

In the first one, the @id http://example.org/anno1 is not resolvable.  This should be the devstore.rerum.io URI of the created annotation.

In the second one, there is no id which proves to me this Annotation was created.

2024-04-23 18:34 UTC, thehabes commented on line/index.mjs
> +router.post('/:id/after', async (req, res) => {
Add javadoc style documentation

```
/**
  * Please
*/
```

2024-04-23 18:34 UTC, thehabes commented on line/index.mjs
> +router.post('/:id/before', async (req, res) => {
Add javadoc style documentation

```
/**
  * Please
*/
```

2024-04-23 18:34 UTC, thehabes commented on line/index.mjs
> +router.delete('/:id', async (req, res) => {
Add javadoc style documentation

```
/**
  * Please
*/
```

2024-04-23 18:34 UTC, thehabes commented on line/index.mjs
> +router.put('/:id', async (req, res) => {
Add javadoc style documentation

```
/**
  * Please
*/
```

2024-04-23 20:06 UTC, thehabes commented
I had gotten the scope a little wrong.  After some conversation with @BhanuKandula5030 here's what we came up with for the scenario I was testing here.

```
{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "@id": "https://devstore.rerum.io/v1/id/6627fc13a1162cbdb9d34a5d"
  "type": "AnnotationCollection",
  "label": "Project - Layer Title",
  "creator": "thehabes",
  "total": 1,
  "first": "https://devstore.rerum.io/v1/id/6627fc3d5cc3848690279f7c",
  "last": "https://devstore.rerum.io/v1/id/6627fc3d5cc3848690279f7c",
  "partOf": "https://static.t-pen.org/6621c63a8168b7592a0bc627/project.json"
}

{
    "@context": "http://www.w3.org/ns/anno.jsonld",
    "@id":"https://devstore.rerum.io/v1/id/6627fc3d5cc3848690279f7c"
    "type": "AnnotationPage",
    "target" : "https://manifest/canvas/1",
    "next": "https://store.rerum.io/v1/id/page2",
    "items": [],
    "partOf": "https://devstore.rerum.io/v1/id/6627fc13a1162cbdb9d34a5d",
    "creator": "thehabes"
}

{
  "@context": "http://www.w3.org/ns/anno.jsonld",
  "@id": "https://devstore.rerum.io/v1/id/662801cbe8afc731e3b58e50",
  "creator": "thehabes",
  "type": "Annotation",
  "motivation": "supplementing",
  "body": {
    "type": "TextualBody",
    "value": "hello world",
    "format": "text/plain",
    "language": "la"
  },
  "target": "https://manifest/canvas/4#xywh=10,20,145,55"
}
```

What you have is an existing Annotation Page and an existing Annotation and they need to be put together.  Be aware of [how a PUT update works](https://store.rerum.io/v1/API.html#update) as you are not "overwriting" the object in place, but rather generating `history`.  This is important because it means you will have to do upstream changes to the Annotation Collection as well, but that will come next.  First, make sure /appendLine works with the provided Page and Annotation.

2024-04-24 01:59 UTC, BhanuKandula5030 commented on line/index.mjs
> +router.post('/:id/after', async (req, res) => {
Updated in the latest code .Thanks

2024-04-24 01:59 UTC, BhanuKandula5030 commented on line/index.mjs
> +router.delete('/:id', async (req, res) => {
Updated in the latest code .Thanks

2024-04-24 01:59 UTC, BhanuKandula5030 commented on line/index.mjs
> +router.put('/:id', async (req, res) => {
Updated in the latest code .Thanks

2024-04-24 02:32 UTC, BhanuKandula5030 commented
Hi @thehabes 

I have made the failing test for the check in the previous code .Now I made the syntax corrections and made it pass .I am Attaching the test case check .All the tests are passing.

<img width="742" alt="image" src="https://github.com/CenterForDigitalHumanities/TPEN-services/assets/113061241/6b47267b-d10d-44c5-aba4-af5fbc7444dc">

2024-04-24 02:39 UTC, BhanuKandula5030 commented
I have updated the append and prepend lone logics and used the https://devstore.rerum.io/v1/id/6627fc3d5cc3848690279f7c real annotation page provided and performed the tests. attaching the get requests of  before POST append line request  and after POST append line request screenshots where you see before as empty items and it got updated after append request  which in corresponds updated in the next in get requests.

![before append](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/113061241/fae777eb-113d-4c81-bdf6-7eb069c09606)
![after append](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/113061241/a6c7c8ed-bb12-4602-b380-8901e9202617)

2024-04-24 02:42 UTC, BhanuKandula5030 commented
I have updated prepend line logics and used the https://devstore.rerum.io/v1/id/6627fc3d5cc3848690279f7c real annotation page provided and performed the tests. attaching the get requests of before POST prepend line request and after POST prepend line request screenshots 
![before prepend](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/113061241/956f99c6-ced8-4fe7-8e96-02441376f461)
![after prepend](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/113061241/5cab8abe-b196-4e68-9dac-adcecd454a60)

2024-05-20 15:09 UTC, closed without merging