101 isvalidid for db controller
CenterForDigitalHumanities/TPEN-services pull request #109
Opened 2024-04-22 16:14 UTC by cubap

2024-04-22 16:14 UTC, cubap commented
midflow. more to come, but this is the hotfix

2024-04-22 23:10 UTC, thehabes requested changes
I performed the following test which I assumed would result in an invalid id.

```javascript
const database = new DatabaseDriver("mongo")
if(database.isValidId("6")){
   console.log("VALID ID '6'.  I can save")
   return await database.save(manifestJSON)
}
else{
   console.log("INVALID ID '6'.  I won't save.")
   return false
}
```
Instead, the logs told me 
> VALID ID '6'.  I can save

If '6' is valid then I am wrong.  My gut instinct is that '6' is not a valid ID.

These were detected as expected

> INVALID ID 'potato' I won't save
> INVALID ID 'anything' I won't save.

2024-04-23 15:54 UTC, cubap commented on database/mongo/__tests__/unit.test.mjs
> +
Not sure what merge is off, but it looks like the `timeout` stuff is lost here...

2024-04-23 20:56 UTC, cubap reviewed
I'm pushing this in because I am rage.

2024-04-23 20:56 UTC, merged