Import projects route and tests
CenterForDigitalHumanities/TPEN-services pull request #121
Opened 2024-06-25 22:25 UTC by jsvoo

2024-07-02 17:41 UTC, thehabes requested changes
Test the endpoint using the following JSON bodies and see if you can make the responses a bit more RESTful.
```JSON
{
   "url": "https://tinydev.rerum.io/plain.txt"
}
```

```JSON
{
   "url": "https://fake.com/id/123123"
}
```

```JSON
{
   "url": 123
}
```
![image](https://github.com/CenterForDigitalHumanities/TPEN-services/assets/3287006/a79fcb3f-37ff-4762-9590-7a22fb696430)

The `@id` of the layer should not be the `@id` of the 'canvas', as seen here in this success response

```JSON
{
   "title":"Kerpen, Kath. Pfarrei St. Martinus Codex 0009 project",
   "@context":"http://t-pen.org/3/context.json",
   "manifest":"https://store.rerum.io/v1/id/667d8064a149c276746683aa",
   "layers":[
      {
         "@id":"https://t-pen.org/TPEN/canvas/105420",
         "@type":"Layer",
         "pages":[
            
         ]
      }
   ],
   "@type":"Project",
   "_id":"6684375379b1439e8e6389d9"
}
```

The line of code is in ImportProject.processLayerFromCanvas()
```
layer["@id"] = canvas["@id"]
```
The layer `@id` will be the store.rerum.io/v1/id/123123123 of some AnnotationCollection in RERUM instead, I believe.

2024-07-02 17:41 UTC, thehabes commented on classes/Project/__tests__/exists_unit.test.mjs
> +  });
remove superfluous `;` and all others like it in this file.

2024-07-02 17:41 UTC, thehabes commented on classes/Project/__tests__/functionality_unit.test.mjs
> +    global.fetch = jest.fn();
remove superfluous `;` and all others like it in this file.

2024-07-02 17:41 UTC, thehabes commented on classes/Project/ImportProject.mjs
> +     return fetch(url)
Gotta catch() somewhere

2024-07-02 17:41 UTC, thehabes commented on classes/Project/ImportProject.mjs
> +  static async fromManifestURL(manifestId) {
Gotta catch() somewhere

2024-07-02 18:52 UTC, thehabes commented on project/index.mjs
> +  utils.respondWithError(res, 405, "Improper request method, please use GET.")
please use POST

2024-07-08 14:56 UTC, cubap approved these changes

2024-07-08 14:56 UTC, merged